// <auto-generated />
namespace OneStopElectronix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Wed001_1911 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wed001_1911));
        
        string IMigrationMetadata.Id
        {
            get { return "201806201611520_Wed001_1911"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
